version: "3.9"

services:

  jupyter:
    image: jupyter/datascience-notebook:latest
    ports:
      - 4321:8888
    #depends_on:
    #  - julia
    volumes:
      - .:/app
    environment:
      - JUPYTER_TOKEN=isetbz
    #   JUPYTER_ENABLE_LAB: "yes"
    # command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"

  # julia:
  #   #build:
  #   #  context: ./
  #   #  dockerfile: Dockerfile
  #   #image: jlai
  #   # depends_on:
  #   #  - jupyter
  # #   # ports:
  # #   #   - 4321:4321
  # #   container_name: jlai
  #   image: julia:1.8.2
  #   command: julia
  # #   volumes:
  # #     - .:/app


# The `docker-compose.yml` file runs both a `Jupyter notebook` and a `Julia` service, and allows to run `Julia` from within the `Jupyter Notebook`.